### ISSUE TITLE
Issue with Xcode 10.1

### ISSUE THREAD

**Issue by Rockwig-GSC** [lyft/set-simulator-location#12]
I get the following message, when trying to set the location on a simulator running 12.1 using xcode 10.1 on macOS 10.14.

`set-simulator-location -c 40.741 -73.989`

`No simulators are currently booted`

Issuing a `xcrun simctl list -j devices` command returns the following, only one device is booted.

```{
  "devices" : {
    "iOS 12.1" : [
      {
        "availability" : "(available)",
        "state" : "Booted",
        "isAvailable" : true,
        "name" : "iPhone 5s",
        ...```

**Comment by qalandarov** [comment]
I second @Rockwig-GSC and add that I tried with 12.0 and 12.1 simulator SDK (both with Xcode 10.1) and still faced the issue... downloading 10.0 again 😞

**Comment by piofusco** [comment]
I am running into the same issue. Would love to get back to UI testing :)

**Comment by sberrevoets** [comment]
#13 should fix this. Can you please try this manually and see if your issue is fixed? If so, we'll release a new version soon.

**Comment by piofusco** [comment]
Looks good to me! 👍

**Comment by Aya-Akl** [comment]
Thank you so much. working now!

**Comment by piofusco** [comment]
How soon can you all cut a new release?

**Comment by sberrevoets** [comment]
We'll aim to have a new release by the end of next week. Thanks for your patience!

**Comment by kidsid-Ixigo** [comment]
How to update to this fix? I mean terminal command?

**Comment by keith** [comment]
This is now fixed in the 1.3.1 release https://github.com/lyft/set-simulator-location/releases

**Comment by GeoSD** [comment]
Hello. Could you please explain how you deal with location permission if you actually deal anything with it? I mean, is it possible to allow it (for testing purposes off course) without any alerts?

**Comment by keith** [comment]
To use this you still need to use the normal location permissions behavior

**Comment by GeoSD** [comment]
> To use this you still need to use the normal location permissions behavior

Thanks for the answer.
