### ISSUE TITLE
Feature Request: Look up simulators by UDID

### ISSUE THREAD

**Issue by qalandarov** [lyft/set-simulator-location#14]
It would be nice to have the option to look up the simulator by its UDID so we can automatically select the right simulator from the build scripts by using `${TARGET_DEVICE_IDENTIFIER}`.

Something like:
`"Usage: set-simulator-location [-c 0 0|-q San Francisco] [-s Simulator Name|-d Simulator UDID]"`

**Comment by keith** [comment]
This has been release as 1.4.0 https://github.com/lyft/set-simulator-location/releases/tag/1.4.0
