### ISSUE TITLE
Please help me in installation 

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [lyft/set-simulator-location#19]
I had install HomeBrew and in currently in project directory. After run set-simulator-location -c 37.7765 -122.3918 command i got error 
###  xcrun: error: unable to find utility "simctl", not a developer tool or in PATH
Running `simctl list` failed

![screen shot 2018-11-30 at 9 56 22 am](https://user-images.githubusercontent.com/6416095/49268635-91942400-f486-11e8-9124-21d62fbb50ee.png)

**Comment by keith** [comment]
It looks like you don't have Xcode installed. You can install Xcode from the Mac App Store https://itunes.apple.com/us/app/xcode/id497799835?mt=12

Just the command line tools (which it looks like you installed at the top of this screenshot) are not enough.

**Comment by SURYAKANTSHARMA** [comment]
i am iOS dev and working on Xcode 10.1

**Comment by SURYAKANTSHARMA** [comment]
@keith  i had installed it in my project directory

**Comment by keith** [comment]
What happens when you run `xcrun simctl` from the command line?

**Comment by keith** [comment]
Ah, it must be your `xcode-select` isn't set. You can probably see this with `xcode-select -p`. You can fix this in the Xcode UI as explained here https://stackoverflow.com/questions/29108172/xcrun-unable-to-find-simctl or from the command line with `sudo xcode-select -s path/to/Xcode.app`

**Comment by SURYAKANTSHARMA** [comment]
Thanks a lot @keith  👍 💯 . I had resolved it.

**Comment by keith** [comment]
No problem!
