### ISSUE TITLE
Feature request: set altitude

### ISSUE THREAD

**Issue by RobertSasak** [lyft/set-simulator-location#21]
Would it be possible to set altitude as well as coordinate?

Replace parameter logic to accept three parameters and return **CLLocationCoordinate3D** instead of **CLLocationCoordinate2D**.
https://github.com/lyft/set-simulator-location/blob/master/sources/coordinate.swift#L14

**Comment by keith** [comment]
Last I checked altitude and heading aren't supported on the simulator

**Comment by RobertSasak** [comment]
More and more I was done with PR, more and more I was afraid of this. I will keep the PR open and maybe in the future can be used. https://github.com/lyft/set-simulator-location/pull/22

Do you mind to share a link to documentation regarding **com.apple.iphonesimulator.simulateLocation**?

**Comment by keith** [comment]
There is no documentation on this. It's all private implementation details I discovered by reverse engineering Xcode. I plan to check again in Xcode 11.

**Comment by akaralar** [comment]
@keith we just stumbled upon this, thanks! may I ask how you reverse engineered this? using hopper or something else?

**Comment by keith** [comment]
Hopper and `strings`

**Comment by keith** [comment]
Update for Xcode 11.5 beta 2, there doesn't appear to be any new functionality related to this

**Comment by camdeardorff** [comment]
I checked Xcode 12 beta 1 and it looks to have the same `simulateLocation...` `path`, `latitude`, `longitude`, and `devices`.

**Comment by KiwiKilian** [comment]
Did anyone look into it for Xcode 14? It's a real bummer, Apple is giving so less info about this...
