### ISSUE TITLE
Error: Your CLT does not support macOS 11.

### ISSUE THREAD

**Issue by saroar** [lyft/set-simulator-location#31]
It is either outdated or was modified.
Please update your CLT or delete it if no updates are available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you an update run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.

alif@Saroars-MacBook-Pro Test % softwareupdate --all --install --force
Software Update Tool

Finding available software
No updates are available.
alif@Saroars-MacBook-Pro Test %

**Comment by keith** [comment]
Can you make sure your `xcode-select -p` is set to the correct Xcode installation path? Otherwise you can change it with `xcode-select -s` or in Xcode's Location preferences

**Comment by saroar** [comment]
@keith 
xcode-select -p
/Applications/Xcode.app/Contents/Developer

**Comment by keith** [comment]
Looks like there are some solutions over here https://github.com/Homebrew/brew/issues/9128#issuecomment-726780049

**Comment by saroar** [comment]
hi thanks @keith my config now work fine then I set 
set-simulator-location -c 60.020201 30.388035
after I run my UI test my Fastlane snapshot after finished my task I check my UI no location is there :(
why the location was not there?
![iPad Pro (12 9-inch) (2nd generation)-createEvent_framed](https://user-images.githubusercontent.com/8770772/102018414-2a502080-3d7e-11eb-87a0-49055ff1f394.png)
u see my current address it empty

**Comment by keith** [comment]
can you check Maps.app instead to make sure it's not logic in your app, also do you see output that the set was successful? also make sure you either specify the simulator or have only 1 simulator
